import MainNavigation from '@/components/layout/main-navigation'
import './globals.css'
import { Inter } from 'next/font/google'
import AuthProvider from '@/components/auth/auth-provider'


// import AuthProvider from '@/components/auth/auth-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
            <AuthProvider>
             <MainNavigation></MainNavigation>
             {children} 
             </AuthProvider>
        </body>
    </html>
  )
}
