import "./globals.css";
import { Inter } from "next/font/google";
import MainHeader from "./main-header";
const inter = Inter({ subsets: ["latin"] });
import { NotificationProvider } from "@/store/notification-context";
import Notis from "./notis/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section>
          <NotificationProvider>
            <MainHeader></MainHeader>
            {children}
            <Notis />
          </NotificationProvider>
        </section>
      </body>
    </html>
  );
}
